export default {
    cod: "200",
    message: 0,
    cnt: 40,
    list: [
        {
            dt: 1622203200,
            main: {
                temp: 305.14,
                feels_like: 313.53,
                temp_min: 303.48,
                temp_max: 305.14,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 1004,
                humidity: 70,
                temp_kf: 1.66,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 40,
            },
            wind: {
                speed: 4.46,
                deg: 260,
                gust: 5.66,
            },
            visibility: 10000,
            pop: 0.2,
            rain: {
                "3h": 0.24,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-28 12:00:00",
        },
        {
            dt: 1622214000,
            main: {
                temp: 304.51,
                feels_like: 312.06,
                temp_min: 303.26,
                temp_max: 304.51,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 1006,
                humidity: 71,
                temp_kf: 1.25,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10n",
                },
            ],
            clouds: {
                all: 60,
            },
            wind: {
                speed: 3.74,
                deg: 249,
                gust: 4.91,
            },
            visibility: 10000,
            pop: 0.24,
            rain: {
                "3h": 0.21,
            },
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-28 15:00:00",
        },
        {
            dt: 1622224800,
            main: {
                temp: 303.72,
                feels_like: 310.46,
                temp_min: 303.01,
                temp_max: 303.72,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 1007,
                humidity: 73,
                temp_kf: 0.71,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10n",
                },
            ],
            clouds: {
                all: 77,
            },
            wind: {
                speed: 3.59,
                deg: 222,
                gust: 4.95,
            },
            visibility: 10000,
            pop: 0.28,
            rain: {
                "3h": 0.25,
            },
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-28 18:00:00",
        },
        {
            dt: 1622235600,
            main: {
                temp: 302.56,
                feels_like: 307.88,
                temp_min: 302.56,
                temp_max: 302.56,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 1005,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10n",
                },
            ],
            clouds: {
                all: 44,
            },
            wind: {
                speed: 3.98,
                deg: 226,
                gust: 5.41,
            },
            visibility: 10000,
            pop: 0.24,
            rain: {
                "3h": 0.15,
            },
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-28 21:00:00",
        },
        {
            dt: 1622246400,
            main: {
                temp: 302.36,
                feels_like: 307.16,
                temp_min: 302.36,
                temp_max: 302.36,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 1006,
                humidity: 74,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10n",
                },
            ],
            clouds: {
                all: 67,
            },
            wind: {
                speed: 3.56,
                deg: 224,
                gust: 4.85,
            },
            visibility: 10000,
            pop: 0.2,
            rain: {
                "3h": 0.16,
            },
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-29 00:00:00",
        },
        {
            dt: 1622257200,
            main: {
                temp: 302.96,
                feels_like: 307.96,
                temp_min: 302.96,
                temp_max: 302.96,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1008,
                humidity: 71,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 2.79,
                deg: 224,
                gust: 4.32,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-29 03:00:00",
        },
        {
            dt: 1622268000,
            main: {
                temp: 303.75,
                feels_like: 309.15,
                temp_min: 303.75,
                temp_max: 303.75,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1008,
                humidity: 68,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.81,
                deg: 206,
                gust: 4.87,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-29 06:00:00",
        },
        {
            dt: 1622278800,
            main: {
                temp: 304.21,
                feels_like: 309.73,
                temp_min: 304.21,
                temp_max: 304.21,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1006,
                humidity: 66,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 97,
            },
            wind: {
                speed: 4.47,
                deg: 228,
                gust: 5.72,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-29 09:00:00",
        },
        {
            dt: 1622289600,
            main: {
                temp: 303.8,
                feels_like: 309.55,
                temp_min: 303.8,
                temp_max: 303.8,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 1006,
                humidity: 69,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 91,
            },
            wind: {
                speed: 4.76,
                deg: 247,
                gust: 5.89,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-29 12:00:00",
        },
        {
            dt: 1622300400,
            main: {
                temp: 303.05,
                feels_like: 309.18,
                temp_min: 303.05,
                temp_max: 303.05,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1007,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 71,
            },
            wind: {
                speed: 3.65,
                deg: 219,
                gust: 4.73,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-29 15:00:00",
        },
        {
            dt: 1622311200,
            main: {
                temp: 302.7,
                feels_like: 308.24,
                temp_min: 302.7,
                temp_max: 302.7,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1008,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 82,
            },
            wind: {
                speed: 3.69,
                deg: 202,
                gust: 4.56,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-29 18:00:00",
        },
        {
            dt: 1622322000,
            main: {
                temp: 302.31,
                feels_like: 306.83,
                temp_min: 302.31,
                temp_max: 302.31,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 1006,
                humidity: 73,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 99,
            },
            wind: {
                speed: 4.9,
                deg: 213,
                gust: 5.74,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-29 21:00:00",
        },
        {
            dt: 1622332800,
            main: {
                temp: 302.02,
                feels_like: 306.53,
                temp_min: 302.02,
                temp_max: 302.02,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1007,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 55,
            },
            wind: {
                speed: 4.3,
                deg: 203,
                gust: 5.02,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-30 00:00:00",
        },
        {
            dt: 1622343600,
            main: {
                temp: 302.4,
                feels_like: 307.26,
                temp_min: 302.4,
                temp_max: 302.4,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1008,
                humidity: 74,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 24,
            },
            wind: {
                speed: 4.86,
                deg: 193,
                gust: 5.1,
            },
            visibility: 10000,
            pop: 0.32,
            rain: {
                "3h": 0.14,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-30 03:00:00",
        },
        {
            dt: 1622354400,
            main: {
                temp: 303.05,
                feels_like: 308.67,
                temp_min: 303.05,
                temp_max: 303.05,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1008,
                humidity: 73,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 33,
            },
            wind: {
                speed: 5.68,
                deg: 218,
                gust: 5.81,
            },
            visibility: 10000,
            pop: 0.36,
            rain: {
                "3h": 0.18,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-30 06:00:00",
        },
        {
            dt: 1622365200,
            main: {
                temp: 303.42,
                feels_like: 309.11,
                temp_min: 303.42,
                temp_max: 303.42,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1006,
                humidity: 71,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            clouds: {
                all: 10,
            },
            wind: {
                speed: 5.69,
                deg: 236,
                gust: 5.94,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-30 09:00:00",
        },
        {
            dt: 1622376000,
            main: {
                temp: 303.2,
                feels_like: 309.32,
                temp_min: 303.2,
                temp_max: 303.2,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 1006,
                humidity: 74,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            clouds: {
                all: 9,
            },
            wind: {
                speed: 5.05,
                deg: 230,
                gust: 5.39,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-30 12:00:00",
        },
        {
            dt: 1622386800,
            main: {
                temp: 302.77,
                feels_like: 308.91,
                temp_min: 302.77,
                temp_max: 302.77,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1007,
                humidity: 77,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            clouds: {
                all: 6,
            },
            wind: {
                speed: 4.69,
                deg: 244,
                gust: 5.6,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-30 15:00:00",
        },
        {
            dt: 1622397600,
            main: {
                temp: 302.43,
                feels_like: 307.55,
                temp_min: 302.43,
                temp_max: 302.43,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1007,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            clouds: {
                all: 5,
            },
            wind: {
                speed: 4.84,
                deg: 230,
                gust: 5.38,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-30 18:00:00",
        },
        {
            dt: 1622408400,
            main: {
                temp: 302.1,
                feels_like: 306.52,
                temp_min: 302.1,
                temp_max: 302.1,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 1005,
                humidity: 74,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            clouds: {
                all: 6,
            },
            wind: {
                speed: 4.4,
                deg: 234,
                gust: 4.85,
            },
            visibility: 10000,
            pop: 0.13,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-30 21:00:00",
        },
        {
            dt: 1622419200,
            main: {
                temp: 301.87,
                feels_like: 306.16,
                temp_min: 301.87,
                temp_max: 301.87,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 1005,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            clouds: {
                all: 7,
            },
            wind: {
                speed: 3.89,
                deg: 225,
                gust: 4.45,
            },
            visibility: 10000,
            pop: 0.09,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-31 00:00:00",
        },
        {
            dt: 1622430000,
            main: {
                temp: 302.39,
                feels_like: 307.02,
                temp_min: 302.39,
                temp_max: 302.39,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1007,
                humidity: 73,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            clouds: {
                all: 8,
            },
            wind: {
                speed: 4.41,
                deg: 222,
                gust: 4.66,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-31 03:00:00",
        },
        {
            dt: 1622440800,
            main: {
                temp: 302.87,
                feels_like: 307.97,
                temp_min: 302.87,
                temp_max: 302.87,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1007,
                humidity: 72,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 22,
            },
            wind: {
                speed: 4.91,
                deg: 231,
                gust: 4.96,
            },
            visibility: 10000,
            pop: 0.2,
            rain: {
                "3h": 0.19,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-31 06:00:00",
        },
        {
            dt: 1622451600,
            main: {
                temp: 303.19,
                feels_like: 308.53,
                temp_min: 303.19,
                temp_max: 303.19,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 1005,
                humidity: 71,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 53,
            },
            wind: {
                speed: 5.71,
                deg: 222,
                gust: 5.84,
            },
            visibility: 10000,
            pop: 0.31,
            rain: {
                "3h": 0.11,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-31 09:00:00",
        },
        {
            dt: 1622462400,
            main: {
                temp: 303.03,
                feels_like: 309.12,
                temp_min: 303.03,
                temp_max: 303.03,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 1004,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 42,
            },
            wind: {
                speed: 5.51,
                deg: 241,
                gust: 6.11,
            },
            visibility: 10000,
            pop: 0.2,
            rain: {
                "3h": 0.13,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-31 12:00:00",
        },
        {
            dt: 1622473200,
            main: {
                temp: 302.61,
                feels_like: 308.01,
                temp_min: 302.61,
                temp_max: 302.61,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 1005,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10n",
                },
            ],
            clouds: {
                all: 45,
            },
            wind: {
                speed: 4.73,
                deg: 244,
                gust: 6.02,
            },
            visibility: 10000,
            pop: 0.28,
            rain: {
                "3h": 0.21,
            },
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-31 15:00:00",
        },
        {
            dt: 1622484000,
            main: {
                temp: 302.39,
                feels_like: 307.45,
                temp_min: 302.39,
                temp_max: 302.39,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 1006,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10n",
                },
            ],
            clouds: {
                all: 71,
            },
            wind: {
                speed: 4.68,
                deg: 256,
                gust: 5.44,
            },
            visibility: 10000,
            pop: 0.21,
            rain: {
                "3h": 0.37,
            },
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-31 18:00:00",
        },
        {
            dt: 1622494800,
            main: {
                temp: 302.04,
                feels_like: 306.77,
                temp_min: 302.04,
                temp_max: 302.04,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 1005,
                humidity: 76,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10n",
                },
            ],
            clouds: {
                all: 74,
            },
            wind: {
                speed: 5.54,
                deg: 266,
                gust: 5.9,
            },
            visibility: 10000,
            pop: 0.31,
            rain: {
                "3h": 0.35,
            },
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-31 21:00:00",
        },
        {
            dt: 1622505600,
            main: {
                temp: 301.75,
                feels_like: 305.88,
                temp_min: 301.75,
                temp_max: 301.75,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 1005,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10n",
                },
            ],
            clouds: {
                all: 54,
            },
            wind: {
                speed: 4.01,
                deg: 244,
                gust: 4.45,
            },
            visibility: 10000,
            pop: 0.28,
            rain: {
                "3h": 0.16,
            },
            sys: {
                pod: "n",
            },
            dt_txt: "2021-06-01 00:00:00",
        },
        {
            dt: 1622516400,
            main: {
                temp: 302.08,
                feels_like: 306.28,
                temp_min: 302.08,
                temp_max: 302.08,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1007,
                humidity: 73,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02d",
                },
            ],
            clouds: {
                all: 22,
            },
            wind: {
                speed: 3.78,
                deg: 230,
                gust: 3.99,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-01 03:00:00",
        },
        {
            dt: 1622527200,
            main: {
                temp: 302.74,
                feels_like: 307.43,
                temp_min: 302.74,
                temp_max: 302.74,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1007,
                humidity: 71,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02d",
                },
            ],
            clouds: {
                all: 22,
            },
            wind: {
                speed: 4.18,
                deg: 245,
                gust: 4.33,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-01 06:00:00",
        },
        {
            dt: 1622538000,
            main: {
                temp: 303.1,
                feels_like: 307.83,
                temp_min: 303.1,
                temp_max: 303.1,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 1005,
                humidity: 69,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03d",
                },
            ],
            clouds: {
                all: 28,
            },
            wind: {
                speed: 5.07,
                deg: 243,
                gust: 5.15,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-01 09:00:00",
        },
        {
            dt: 1622548800,
            main: {
                temp: 302.87,
                feels_like: 307.97,
                temp_min: 302.87,
                temp_max: 302.87,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 1005,
                humidity: 72,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02d",
                },
            ],
            clouds: {
                all: 21,
            },
            wind: {
                speed: 5.15,
                deg: 236,
                gust: 5.68,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-01 12:00:00",
        },
        {
            dt: 1622559600,
            main: {
                temp: 302.36,
                feels_like: 307.16,
                temp_min: 302.36,
                temp_max: 302.36,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 1006,
                humidity: 74,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            clouds: {
                all: 5,
            },
            wind: {
                speed: 5.7,
                deg: 243,
                gust: 6.34,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-06-01 15:00:00",
        },
        {
            dt: 1622570400,
            main: {
                temp: 302.04,
                feels_like: 306.38,
                temp_min: 302.04,
                temp_max: 302.04,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1007,
                humidity: 74,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            clouds: {
                all: 10,
            },
            wind: {
                speed: 4.18,
                deg: 242,
                gust: 4.57,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-06-01 18:00:00",
        },
        {
            dt: 1622581200,
            main: {
                temp: 301.53,
                feels_like: 305.53,
                temp_min: 301.53,
                temp_max: 301.53,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 1005,
                humidity: 76,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 21,
            },
            wind: {
                speed: 3.43,
                deg: 260,
                gust: 3.64,
            },
            visibility: 10000,
            pop: 0.2,
            rain: {
                "3h": 0.11,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-01 21:00:00",
        },
        {
            dt: 1622592000,
            main: {
                temp: 301.28,
                feels_like: 305.1,
                temp_min: 301.28,
                temp_max: 301.28,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 1005,
                humidity: 77,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03d",
                },
            ],
            clouds: {
                all: 25,
            },
            wind: {
                speed: 3.11,
                deg: 266,
                gust: 3.17,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-02 00:00:00",
        },
        {
            dt: 1622602800,
            main: {
                temp: 301.74,
                feels_like: 305.68,
                temp_min: 301.74,
                temp_max: 301.74,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1007,
                humidity: 74,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03d",
                },
            ],
            clouds: {
                all: 43,
            },
            wind: {
                speed: 3.31,
                deg: 266,
                gust: 3.23,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-02 03:00:00",
        },
        {
            dt: 1622613600,
            main: {
                temp: 302.64,
                feels_like: 306.98,
                temp_min: 302.64,
                temp_max: 302.64,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1007,
                humidity: 70,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03d",
                },
            ],
            clouds: {
                all: 36,
            },
            wind: {
                speed: 4.51,
                deg: 264,
                gust: 3.94,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-02 06:00:00",
        },
        {
            dt: 1622624400,
            main: {
                temp: 302.93,
                feels_like: 307.43,
                temp_min: 302.93,
                temp_max: 302.93,
                pressure: 1007,
                sea_level: 1007,
                grnd_level: 1006,
                humidity: 69,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            clouds: {
                all: 7,
            },
            wind: {
                speed: 4.88,
                deg: 258,
                gust: 4.61,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-02 09:00:00",
        },
    ],
    city: {
        id: 1275339,
        name: "Mumbai",
        coord: {
            lat: 19.0144,
            lon: 72.8479,
        },
        country: "IN",
        population: 1000000,
        timezone: 19800,
        sunrise: 1622161865,
        sunset: 1622209260,
    },
};
