export default {
    cod: "200",
    message: 0,
    cnt: 40,
    list: [
        {
            dt: 1622149200,
            main: {
                temp: 289.11,
                feels_like: 289.16,
                temp_min: 288.66,
                temp_max: 289.11,
                pressure: 1015,
                sea_level: 1015,
                grnd_level: 997,
                humidity: 92,
                temp_kf: 0.45,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 80,
            },
            wind: {
                speed: 0.66,
                deg: 100,
                gust: 0.66,
            },
            visibility: 10000,
            pop: 0.4,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-27 21:00:00",
        },
        {
            dt: 1622160000,
            main: {
                temp: 288.5,
                feels_like: 288.55,
                temp_min: 287.28,
                temp_max: 288.5,
                pressure: 1015,
                sea_level: 1015,
                grnd_level: 996,
                humidity: 94,
                temp_kf: 1.22,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 82,
            },
            wind: {
                speed: 1.16,
                deg: 125,
                gust: 1.2,
            },
            visibility: 10000,
            pop: 0.38,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-28 00:00:00",
        },
        {
            dt: 1622170800,
            main: {
                temp: 288.48,
                feels_like: 288.47,
                temp_min: 288.17,
                temp_max: 288.48,
                pressure: 1014,
                sea_level: 1014,
                grnd_level: 996,
                humidity: 92,
                temp_kf: 0.31,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 85,
            },
            wind: {
                speed: 1.03,
                deg: 206,
                gust: 1.42,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-28 03:00:00",
        },
        {
            dt: 1622181600,
            main: {
                temp: 288.39,
                feels_like: 288.4,
                temp_min: 288.39,
                temp_max: 288.39,
                pressure: 1014,
                sea_level: 1014,
                grnd_level: 996,
                humidity: 93,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 94,
            },
            wind: {
                speed: 1.37,
                deg: 239,
                gust: 2.12,
            },
            visibility: 10000,
            pop: 0.4,
            rain: {
                "3h": 0.42,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-28 06:00:00",
        },
        {
            dt: 1622192400,
            main: {
                temp: 292.93,
                feels_like: 292.77,
                temp_min: 292.93,
                temp_max: 292.93,
                pressure: 1013,
                sea_level: 1013,
                grnd_level: 996,
                humidity: 69,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 94,
            },
            wind: {
                speed: 2,
                deg: 265,
                gust: 3.3,
            },
            visibility: 10000,
            pop: 0.62,
            rain: {
                "3h": 1.01,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-28 09:00:00",
        },
        {
            dt: 1622203200,
            main: {
                temp: 290.89,
                feels_like: 290.83,
                temp_min: 290.89,
                temp_max: 290.89,
                pressure: 1013,
                sea_level: 1013,
                grnd_level: 995,
                humidity: 81,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 97,
            },
            wind: {
                speed: 1.85,
                deg: 235,
                gust: 3.33,
            },
            visibility: 10000,
            pop: 0.58,
            rain: {
                "3h": 0.15,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-28 12:00:00",
        },
        {
            dt: 1622214000,
            main: {
                temp: 293.69,
                feels_like: 293.24,
                temp_min: 293.69,
                temp_max: 293.69,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 994,
                humidity: 55,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 65,
            },
            wind: {
                speed: 1.93,
                deg: 236,
                gust: 2.27,
            },
            visibility: 10000,
            pop: 0.12,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-28 15:00:00",
        },
        {
            dt: 1622224800,
            main: {
                temp: 290.78,
                feels_like: 290.37,
                temp_min: 290.78,
                temp_max: 290.78,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 993,
                humidity: 68,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 77,
            },
            wind: {
                speed: 1.46,
                deg: 279,
                gust: 1.45,
            },
            visibility: 10000,
            pop: 0.1,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-28 18:00:00",
        },
        {
            dt: 1622235600,
            main: {
                temp: 289.85,
                feels_like: 289.43,
                temp_min: 289.85,
                temp_max: 289.85,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 993,
                humidity: 71,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 96,
            },
            wind: {
                speed: 1.07,
                deg: 298,
                gust: 1.14,
            },
            visibility: 10000,
            pop: 0.3,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-28 21:00:00",
        },
        {
            dt: 1622246400,
            main: {
                temp: 288.47,
                feels_like: 288.15,
                temp_min: 288.47,
                temp_max: 288.47,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 991,
                humidity: 80,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10n",
                },
            ],
            clouds: {
                all: 98,
            },
            wind: {
                speed: 0.61,
                deg: 210,
                gust: 0.77,
            },
            visibility: 10000,
            pop: 0.32,
            rain: {
                "3h": 0.24,
            },
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-29 00:00:00",
        },
        {
            dt: 1622257200,
            main: {
                temp: 288.73,
                feels_like: 288.43,
                temp_min: 288.73,
                temp_max: 288.73,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 991,
                humidity: 80,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 99,
            },
            wind: {
                speed: 1.3,
                deg: 252,
                gust: 2.43,
            },
            visibility: 10000,
            pop: 0.14,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-29 03:00:00",
        },
        {
            dt: 1622268000,
            main: {
                temp: 291.23,
                feels_like: 290.84,
                temp_min: 291.23,
                temp_max: 291.23,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 991,
                humidity: 67,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 99,
            },
            wind: {
                speed: 3.52,
                deg: 337,
                gust: 3.95,
            },
            visibility: 10000,
            pop: 0.02,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-29 06:00:00",
        },
        {
            dt: 1622278800,
            main: {
                temp: 291.96,
                feels_like: 291.44,
                temp_min: 291.96,
                temp_max: 291.96,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 991,
                humidity: 59,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 5.54,
                deg: 7,
                gust: 6.62,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-29 09:00:00",
        },
        {
            dt: 1622289600,
            main: {
                temp: 291.46,
                feels_like: 290.89,
                temp_min: 291.46,
                temp_max: 291.46,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 992,
                humidity: 59,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 97,
            },
            wind: {
                speed: 5.27,
                deg: 6,
                gust: 6.35,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-29 12:00:00",
        },
        {
            dt: 1622300400,
            main: {
                temp: 291.18,
                feels_like: 290.58,
                temp_min: 291.18,
                temp_max: 291.18,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 992,
                humidity: 59,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 93,
            },
            wind: {
                speed: 4.19,
                deg: 20,
                gust: 4.72,
            },
            visibility: 10000,
            pop: 0.06,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-29 15:00:00",
        },
        {
            dt: 1622311200,
            main: {
                temp: 288.56,
                feels_like: 288.04,
                temp_min: 288.56,
                temp_max: 288.56,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 993,
                humidity: 72,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 96,
            },
            wind: {
                speed: 3.76,
                deg: 35,
                gust: 6.98,
            },
            visibility: 10000,
            pop: 0.02,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-29 18:00:00",
        },
        {
            dt: 1622322000,
            main: {
                temp: 286.43,
                feels_like: 285.88,
                temp_min: 286.43,
                temp_max: 286.43,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 994,
                humidity: 79,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 4.22,
                deg: 36,
                gust: 9.95,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-29 21:00:00",
        },
        {
            dt: 1622332800,
            main: {
                temp: 285.09,
                feels_like: 284.59,
                temp_min: 285.09,
                temp_max: 285.09,
                pressure: 1013,
                sea_level: 1013,
                grnd_level: 995,
                humidity: 86,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 4.81,
                deg: 31,
                gust: 9.82,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-30 00:00:00",
        },
        {
            dt: 1622343600,
            main: {
                temp: 283.37,
                feels_like: 282.48,
                temp_min: 283.37,
                temp_max: 283.37,
                pressure: 1014,
                sea_level: 1014,
                grnd_level: 997,
                humidity: 78,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 5.79,
                deg: 23,
                gust: 10.17,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-30 03:00:00",
        },
        {
            dt: 1622354400,
            main: {
                temp: 285.32,
                feels_like: 284.24,
                temp_min: 285.32,
                temp_max: 285.32,
                pressure: 1015,
                sea_level: 1015,
                grnd_level: 998,
                humidity: 63,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 5.76,
                deg: 24,
                gust: 7.96,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-30 06:00:00",
        },
        {
            dt: 1622365200,
            main: {
                temp: 289.13,
                feels_like: 288.04,
                temp_min: 289.13,
                temp_max: 289.13,
                pressure: 1016,
                sea_level: 1016,
                grnd_level: 998,
                humidity: 48,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 88,
            },
            wind: {
                speed: 6.19,
                deg: 29,
                gust: 7.54,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-30 09:00:00",
        },
        {
            dt: 1622376000,
            main: {
                temp: 289.77,
                feels_like: 288.58,
                temp_min: 289.77,
                temp_max: 289.77,
                pressure: 1017,
                sea_level: 1017,
                grnd_level: 999,
                humidity: 42,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 84,
            },
            wind: {
                speed: 6.32,
                deg: 42,
                gust: 7.35,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-30 12:00:00",
        },
        {
            dt: 1622386800,
            main: {
                temp: 288.2,
                feels_like: 286.99,
                temp_min: 288.2,
                temp_max: 288.2,
                pressure: 1018,
                sea_level: 1018,
                grnd_level: 1000,
                humidity: 47,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 97,
            },
            wind: {
                speed: 6.32,
                deg: 46,
                gust: 7.79,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-30 15:00:00",
        },
        {
            dt: 1622397600,
            main: {
                temp: 284.97,
                feels_like: 283.62,
                temp_min: 284.97,
                temp_max: 284.97,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1001,
                humidity: 54,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 64,
            },
            wind: {
                speed: 5.21,
                deg: 36,
                gust: 10.25,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-30 18:00:00",
        },
        {
            dt: 1622408400,
            main: {
                temp: 282.97,
                feels_like: 280.51,
                temp_min: 282.97,
                temp_max: 282.97,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1003,
                humidity: 59,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 73,
            },
            wind: {
                speed: 5.02,
                deg: 35,
                gust: 12.45,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-30 21:00:00",
        },
        {
            dt: 1622419200,
            main: {
                temp: 281.46,
                feels_like: 278.61,
                temp_min: 281.46,
                temp_max: 281.46,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1003,
                humidity: 62,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 78,
            },
            wind: {
                speed: 5.05,
                deg: 45,
                gust: 13.27,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2021-05-31 00:00:00",
        },
        {
            dt: 1622430000,
            main: {
                temp: 281.37,
                feels_like: 278.44,
                temp_min: 281.37,
                temp_max: 281.37,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1003,
                humidity: 60,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 5.17,
                deg: 48,
                gust: 12.85,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-31 03:00:00",
        },
        {
            dt: 1622440800,
            main: {
                temp: 285.58,
                feels_like: 283.95,
                temp_min: 285.58,
                temp_max: 285.58,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1004,
                humidity: 41,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 83,
            },
            wind: {
                speed: 6.33,
                deg: 64,
                gust: 10.4,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-31 06:00:00",
        },
        {
            dt: 1622451600,
            main: {
                temp: 287.32,
                feels_like: 285.76,
                temp_min: 287.32,
                temp_max: 287.32,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1003,
                humidity: 37,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 90,
            },
            wind: {
                speed: 6.25,
                deg: 75,
                gust: 8.26,
            },
            visibility: 10000,
            pop: 0.08,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-31 09:00:00",
        },
        {
            dt: 1622462400,
            main: {
                temp: 286.15,
                feels_like: 284.81,
                temp_min: 286.15,
                temp_max: 286.15,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1003,
                humidity: 50,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 95,
            },
            wind: {
                speed: 4.84,
                deg: 91,
                gust: 7.55,
            },
            visibility: 10000,
            pop: 0.26,
            rain: {
                "3h": 0.15,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-31 12:00:00",
        },
        {
            dt: 1622473200,
            main: {
                temp: 285.29,
                feels_like: 284.15,
                temp_min: 285.29,
                temp_max: 285.29,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1003,
                humidity: 61,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.41,
                deg: 61,
                gust: 7.29,
            },
            visibility: 10000,
            pop: 0.54,
            rain: {
                "3h": 0.59,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-31 15:00:00",
        },
        {
            dt: 1622484000,
            main: {
                temp: 284.63,
                feels_like: 283.35,
                temp_min: 284.63,
                temp_max: 284.63,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1003,
                humidity: 58,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.12,
                deg: 101,
                gust: 6.49,
            },
            visibility: 10000,
            pop: 0.34,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-31 18:00:00",
        },
        {
            dt: 1622494800,
            main: {
                temp: 283.92,
                feels_like: 282.65,
                temp_min: 283.92,
                temp_max: 283.92,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1003,
                humidity: 61,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.3,
                deg: 57,
                gust: 8,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-05-31 21:00:00",
        },
        {
            dt: 1622505600,
            main: {
                temp: 283.58,
                feels_like: 282.35,
                temp_min: 283.58,
                temp_max: 283.58,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1003,
                humidity: 64,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.58,
                deg: 62,
                gust: 9.53,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-01 00:00:00",
        },
        {
            dt: 1622516400,
            main: {
                temp: 282.95,
                feels_like: 281.05,
                temp_min: 282.95,
                temp_max: 282.95,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1003,
                humidity: 71,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.7,
                deg: 66,
                gust: 10.05,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-01 03:00:00",
        },
        {
            dt: 1622527200,
            main: {
                temp: 284.31,
                feels_like: 283.2,
                temp_min: 284.31,
                temp_max: 284.31,
                pressure: 1022,
                sea_level: 1022,
                grnd_level: 1004,
                humidity: 66,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 4.15,
                deg: 80,
                gust: 8.71,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-01 06:00:00",
        },
        {
            dt: 1622538000,
            main: {
                temp: 286.58,
                feels_like: 285.49,
                temp_min: 286.58,
                temp_max: 286.58,
                pressure: 1022,
                sea_level: 1022,
                grnd_level: 1004,
                humidity: 58,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 4.8,
                deg: 95,
                gust: 6.52,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-01 09:00:00",
        },
        {
            dt: 1622548800,
            main: {
                temp: 287.95,
                feels_like: 286.97,
                temp_min: 287.95,
                temp_max: 287.95,
                pressure: 1022,
                sea_level: 1022,
                grnd_level: 1004,
                humidity: 57,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.54,
                deg: 75,
                gust: 6.6,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-01 12:00:00",
        },
        {
            dt: 1622559600,
            main: {
                temp: 287.84,
                feels_like: 286.98,
                temp_min: 287.84,
                temp_max: 287.84,
                pressure: 1023,
                sea_level: 1023,
                grnd_level: 1005,
                humidity: 62,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 2.52,
                deg: 104,
                gust: 7.49,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-01 15:00:00",
        },
        {
            dt: 1622570400,
            main: {
                temp: 286.77,
                feels_like: 285.99,
                temp_min: 286.77,
                temp_max: 286.77,
                pressure: 1024,
                sea_level: 1024,
                grnd_level: 1006,
                humidity: 69,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 2.54,
                deg: 87,
                gust: 6.46,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2021-06-01 18:00:00",
        },
    ],
    city: {
        id: 524901,
        name: "Moscow",
        coord: {
            lat: 55.7522,
            lon: 37.6156,
        },
        country: "RU",
        population: 0,
        timezone: 10800,
        sunrise: 1622077151,
        sunset: 1622138073,
    },
};
