import Head from "next/head";
import SearchBar from "../components/SearchBar";
import TodayCond from "../components/TodayCond";
import WeekCond from "../components/WeekCond";

export default function Home() {
    return (
        <div className="flex flex-col h-screen space-y-2 p-5 items-start bg-gray-50 overflow-x-hidden">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* SearchBar */}
            <SearchBar />

            {/* WeekCond */}
            <WeekCond />

            {/* TodayCond */}
            <TodayCond />
        </div>
    );
}
